### ISSUE TITLE
TODO for version 1.0

### ISSUE THREAD

**Issue by zklosko** [zklosko/spirit-of-radio#1]
I'm starting this issue to track the things that need to be done for the theme to be (basically) completed for the theme to be "finished".

- [x] Reconsider theme fonts. The body fonts look a little off.

- [x] Finish CSS theming for sidebar on `layout/docs`. Aiming to have it look like black section of the `index` page; `layout/splash`. Sidebar doesn't fully extend to edge of browser.

- [x] Add, document front-matter options

- [x] DOCUMENTATION

- [x] Add CSS style for code blocks

**Comment by zklosko** [comment]
Version 1.0 has been committed
